package tb;

import com.alibaba.triver.triver_shop.newShop.data.h;
import com.android.alibaba.ip.runtime.IpChange;
import com.o2o.ad.a;
import java.util.HashMap;

/* loaded from: classes4.dex */
public class ewy {
    public static volatile transient /* synthetic */ IpChange $ipChange = null;
    public static final int T_ASK_ALL = 30038;
    public static final int T_AVATAR_GROUPS = 46003;
    public static final int T_BOTTOM_BAR = 20002;
    public static final int T_BOTTOM_BAR_BUY = 20006;
    public static final int T_BOTTOM_BAR_BUY_JHS = 20012;
    public static final int T_BOTTOM_BAR_CART = 20007;
    public static final int T_BOTTOM_BAR_FAV = 20008;
    public static final int T_BOTTOM_BAR_GRADIENT = 20020;
    public static final int T_BOTTOM_BAR_ICON = 20017;
    public static final int T_BOTTOM_BAR_LINE = 20010;
    public static final int T_BOTTOM_BAR_PRE_SALE = 20015;
    public static final int T_BOTTOM_BAR_REMINDER = 20018;
    public static final int T_BOTTOM_BAR_RESERVE = 20019;
    public static final int T_BOTTOM_BAR_SECKILL = 20003;
    public static final int T_BOTTOM_BAR_SHOP = 20009;
    public static final int T_BOTTOM_BAR_SM_CART = 20013;
    public static final int T_BOTTOM_BAR_WAIT_FOR_SATRT = 20016;
    public static final int T_BOTTOM_BAR_WANG_WANG = 20011;
    public static final int T_BUTTON_CONTAINER = 47001;
    public static final int T_CHINA_QUALITY_PRICE = 44001;
    public static final int T_COMBO = 30030;
    public static final int T_COMMON_PICTURE_JUMPER = 30025;
    public static final int T_COMPOSITE_CONTAINER = 35004;
    public static final int T_COUPON = 35008;
    public static final int T_COUPON_INFO = 30035;
    public static final int T_CT_APP_SEGMENT = 80000;
    public static final int T_CT_PACK_TRADE = 80001;
    public static final int T_CUSTOM_MODULE = 35022;
    public static final int T_DESC_CHARITY = 35037;
    public static final int T_DESC_DIVIDER = 35028;
    public static final int T_DESC_GIF = 90001;
    public static final int T_DESC_RECOMMEND = 21009;
    public static final int T_DETAIL = 21001;
    public static final int T_DETAILI_SALE_POINT = 35030;
    public static final int T_DETAIL_DESC = 21008;
    public static final int T_DETAIL_FULLTEXT = 35023;
    public static final int T_DETAIL_HOME = 21010;
    public static final int T_DETAIL_INFO = 21006;
    public static final int T_DETAIL_NAVI_BAR = 21002;
    public static final int T_DETAIL_NAVI_ITEM = 21004;
    public static final int T_DETAIL_NAVI_TAB = 21003;
    public static final int T_DETAIL_NAVI_TAB_ITEM = 21005;
    public static final int T_DINAMIC = 30045;
    public static final int T_DINAMIC_O2O = 30046;
    public static final int T_DIVISION = 30020;
    public static final int T_DIVISION_TITLE = 35009;
    public static final int T_ENTRANCE = 46001;
    public static final int T_GOODS_MATCHING = 35013;
    public static final int T_GOOD_QUALITY = 30036;
    public static final int T_H5 = 34002;
    public static final int T_HK_TIP = 42001;
    public static final int T_HOT_AREA = 35019;
    public static final int T_HOT_BOTTOM_BAR = 43002;
    public static final int T_IMAGE_BAR = 30027;
    public static final int T_ITEM_INFO = 35007;
    public static final int T_ITEM_INFO_2 = 35012;
    public static final int T_JHS_APP_SEGMENT = 70000;
    public static final int T_JHS_BOTTOM_BAR = 40003;
    public static final int T_JHS_PRICE = 40002;
    public static final int T_JHS_WAITING_BOTTOM_BAR = 40004;
    public static final int T_MAGIC_PAIRS = 30024;
    public static final int T_MAIN_VIEW_CONTAINER = 47002;
    public static final int T_MARKET_BOTTOM_BAR = 41004;
    public static final int T_MARKET_HOT_ACTIVITY = 41002;
    public static final int T_MARKET_PRESALE_BOTTOM_BAR = 41005;
    public static final int T_MARKET_RECOMMEND = 41001;
    public static final int T_MARKET_TIME_LIMIT = 41003;
    public static final int T_MODEL_WEAR = 35020;
    public static final int T_MULTISTAGE = 46002;
    public static final int T_MULTI_PIC_CONTAINER = 35001;
    public static final int T_NAVI_BAR = 20001;
    public static final int T_NAVI_ITEM = 20004;
    public static final int T_NAVI_ITEM_GROUP = 20005;
    public static final int T_NB_VIDEO = 35024;
    public static final int T_NEW_TITLE = 30031;
    public static final int T_O2O = 30029;
    public static final int T_OFFLINE_STORE = 35032;
    public static final int T_PACKING_LIST = 35018;
    public static final int T_PAIRS = 30022;
    public static final int T_PICTURE_3D = 35029;
    public static final int T_PICTURE_JUMPER = 35011;
    public static final int T_PIC_CONTAINER = 35017;
    public static final int T_PIC_GALLERY = 30001;
    public static final int T_PIC_WITH_TITLE = 35016;
    public static final int T_PLACE_HOLDER = 35027;
    public static final int T_PRESALE_BOTTOM_BAR = 43001;
    public static final int T_PRICE = 30003;
    public static final int T_PRICE_TAGS = 30004;
    public static final int T_PRICE_XINXUAN = 30040;
    public static final int T_PRODUCT_INFO = 35015;
    public static final int T_QIANG_GOU_PRICE = 44002;
    public static final int T_QUALITY = 35026;
    @Deprecated
    public static final int T_QUESTION_ALL = 30028;
    public static final int T_RATE_CONTENTS = 30015;
    public static final int T_RATE_HEADER = 30013;
    public static final int T_RATE_KEYWORDS = 30014;
    public static final int T_RELATED_PRODUCTION = 30032;
    public static final int T_RIGHTS = 30008;
    public static final int T_RIGHTS_VERTICAL = 30009;
    public static final int T_SCROLLABLE_CONTAINER = 35002;
    public static final int T_SERVICE = 35021;
    public static final int T_SHOP_CARD_RECOMMEND = 30039;
    public static final int T_SHOP_HEADER = 30017;
    public static final int T_SHOP_INFO = 30018;
    public static final int T_SHOP_INFO_ITEM = 48001;
    public static final int T_SHOP_PROMOTION = 30011;
    public static final int T_SHOP_PROMOTION_2 = 30034;
    public static final int T_SIZE_CHART = 35014;
    public static final int T_SKU = 30012;
    public static final int T_SKU_BAR = 35010;
    public static final int T_SPLITABLE_CONTAINER = 35003;
    public static final int T_SUBINFO = 30007;
    public static final int T_SYS_BUTTON = 10001;
    public static final int T_SYS_LABEL = 10002;
    public static final int T_SYS_LIST = 10003;
    public static final int T_T3D_MODULE = 35033;
    public static final int T_TB_APP_SEGMENT = 50000;
    public static final int T_TIP = 30005;
    public static final int T_TITLE = 30002;
    public static final int T_TMALL_FEATURE = 30044;
    public static final int T_TMALL_VIP = 30033;
    public static final int T_TM_APP_SEGMENT = 60000;
    public static final int T_TM_NAVI_BAR = 36001;
    public static final int T_TM_PIC_GALLERY = 36002;
    public static final int T_TM_STORE_BANNER = 36003;
    public static final int T_TM_STORE_RECMD = 36004;
    public static final int T_UNIFORM_PRICE = 40010;
    public static final int T_UNKNOWN = 0;
    public static final int T_USER_TALK = 35031;
    public static final int T_VESSEL = 35035;
    public static final int T_VIDEO_CONTAINER = 35040;
    public static final int T_VIDEO_INFO = 35041;
    public static final int T_WEEX = 35034;
    public static final int T_WEEX_CONTAINER = 21007;
    public static final int T_WEEX_VESSEL = 35036;
    public static final int T_XSKU = 30047;
    public static final int T_ZHONG_REN_TUAN_PROGRESSBAR = 30037;
    public static final HashMap<String, Integer> m;

    static {
        kge.a(291301794);
        m = new HashMap<>();
        tpc.a("com.taobao.android.detail.sdk.vmodel.ViewModelType");
        m.put("sys_button", 10001);
        m.put("sys_label", 10002);
        m.put("sys_list", 10003);
        m.put("navi_bar", 20001);
        m.put("navi_item", 20004);
        m.put("navi_item_group", 20005);
        m.put("pic_gallery", 30001);
        m.put("title_share", 30002);
        m.put("price", 30003);
        m.put("price_tags", 30004);
        m.put("subinfo", 30007);
        m.put("rights", 30008);
        m.put("right_vertical", 30009);
        m.put("shop_promotion", 30011);
        m.put("sku", 30012);
        m.put("xsku", Integer.valueOf((int) T_XSKU));
        m.put("rate_header", 30013);
        m.put("rate_tags", 30014);
        m.put("rate_single", 30015);
        m.put("shop_header", 30017);
        m.put("shop_info", 30018);
        m.put(onk.NAME, 30020);
        m.put("pairs", 30022);
        m.put("common_picture_jumper", Integer.valueOf((int) T_COMMON_PICTURE_JUMPER));
        m.put("image_bar", Integer.valueOf((int) T_IMAGE_BAR));
        m.put("question_all", Integer.valueOf((int) T_QUESTION_ALL));
        m.put(a.O2O_URL, Integer.valueOf((int) T_O2O));
        m.put("combo", Integer.valueOf((int) T_COMBO));
        m.put("h5", Integer.valueOf((int) T_H5));
        m.put("desc_simple_text", Integer.valueOf((int) T_DETAIL_FULLTEXT));
        m.put("product_relate", Integer.valueOf((int) T_RELATED_PRODUCTION));
        m.put("tmall_vip_shop", Integer.valueOf((int) T_TMALL_VIP));
        m.put("promotion_info", Integer.valueOf((int) T_SHOP_PROMOTION_2));
        m.put("coupon_info", Integer.valueOf((int) T_COUPON_INFO));
        m.put("good_quality", Integer.valueOf((int) T_GOOD_QUALITY));
        m.put("desc_3d_model", Integer.valueOf((int) T_T3D_MODULE));
        m.put("ask_all", Integer.valueOf((int) T_ASK_ALL));
        m.put("shop_card_rcmd", Integer.valueOf((int) T_SHOP_CARD_RECOMMEND));
        m.put("price_xinxuan", Integer.valueOf((int) T_PRICE_XINXUAN));
        m.put("tb_tmall_feature", Integer.valueOf((int) T_TMALL_FEATURE));
        m.put("uniform_price", Integer.valueOf((int) T_UNIFORM_PRICE));
        m.put("vessel", Integer.valueOf((int) T_WEEX_VESSEL));
        m.put("magic_pairs", Integer.valueOf((int) T_MAGIC_PAIRS));
        m.put("price_jhs", 40002);
        m.put("recommend_chaoshi", Integer.valueOf((int) T_MARKET_RECOMMEND));
        m.put("hot_activity_chaoshi", Integer.valueOf((int) T_MARKET_HOT_ACTIVITY));
        m.put("timelimit_activity_chaoshi", Integer.valueOf((int) T_MARKET_TIME_LIMIT));
        m.put(h.bottomBarArea, 20002);
        m.put("bottom_bar_group_jhs", 40003);
        m.put("bottom_bar_group_waiting", 40004);
        m.put("bottom_bar_group_market", Integer.valueOf((int) T_MARKET_BOTTOM_BAR));
        m.put("bottom_bar_seckill", 20003);
        m.put("bottom_bar_hot", Integer.valueOf((int) T_HOT_BOTTOM_BAR));
        m.put("bottom_bar_buy", 20006);
        m.put("bottom_bar_buy_jhs", 20012);
        m.put("bottom_bar_sm_cart", 20013);
        m.put("bottom_bar_cart", 20007);
        m.put("bottom_bar_fav", 20008);
        m.put("bottom_bar_shop", 20009);
        m.put("bottom_bar_ww", 20011);
        m.put("bottom_bar_presale", Integer.valueOf((int) T_BOTTOM_BAR_PRE_SALE));
        m.put("bottom_bar_timing_shelves", Integer.valueOf((int) T_BOTTOM_BAR_WAIT_FOR_SATRT));
        m.put("bottom_bar_gradient", Integer.valueOf((int) T_BOTTOM_BAR_GRADIENT));
        m.put("bottom_bar_icon", Integer.valueOf((int) T_BOTTOM_BAR_ICON));
        m.put("bottom_bar_remind", Integer.valueOf((int) T_BOTTOM_BAR_REMINDER));
        m.put("bottom_bar_reserve", Integer.valueOf((int) T_BOTTOM_BAR_RESERVE));
        m.put("bottom_bar_group_presale", Integer.valueOf((int) T_PRESALE_BOTTOM_BAR));
        m.put("bottom_bar_group_market_presale", Integer.valueOf((int) T_MARKET_PRESALE_BOTTOM_BAR));
        m.put("price_cnquality", Integer.valueOf((int) T_CHINA_QUALITY_PRICE));
        m.put("price_qianggou", Integer.valueOf((int) T_QIANG_GOU_PRICE));
        m.put("multi_pic_container", Integer.valueOf((int) T_MULTI_PIC_CONTAINER));
        m.put("desc_scrollable_container", Integer.valueOf((int) T_SCROLLABLE_CONTAINER));
        m.put("desc_splitable_container", Integer.valueOf((int) T_SPLITABLE_CONTAINER));
        m.put("desc_size_chart_group", Integer.valueOf((int) T_COMPOSITE_CONTAINER));
        m.put("desc_single_image", Integer.valueOf((int) T_PIC_CONTAINER));
        m.put("desc_video", Integer.valueOf((int) T_NB_VIDEO));
        m.put("desc_item_info", Integer.valueOf((int) T_ITEM_INFO));
        m.put("desc_coupon", Integer.valueOf((int) T_COUPON));
        m.put("desc_user_talk", Integer.valueOf((int) T_USER_TALK));
        m.put("desc_division_title", Integer.valueOf((int) T_DIVISION_TITLE));
        m.put("desc_sku_bar", Integer.valueOf((int) T_SKU_BAR));
        m.put("desc_pic_jumper", Integer.valueOf((int) T_PICTURE_JUMPER));
        m.put("desc_simple_item_info", Integer.valueOf((int) T_ITEM_INFO_2));
        m.put("desc_goods_matching", Integer.valueOf((int) T_GOODS_MATCHING));
        m.put("desc_single_size_chart", Integer.valueOf((int) T_SIZE_CHART));
        m.put("desc_place_holder", Integer.valueOf((int) T_PLACE_HOLDER));
        m.put("desc_product_info", Integer.valueOf((int) T_PRODUCT_INFO));
        m.put("desc_pic_with_title", Integer.valueOf((int) T_PIC_WITH_TITLE));
        m.put("desc_packing_list", Integer.valueOf((int) T_PACKING_LIST));
        m.put("desc_hot_area", Integer.valueOf((int) T_HOT_AREA));
        m.put("model_wear", Integer.valueOf((int) T_MODEL_WEAR));
        m.put("desc_service", Integer.valueOf((int) T_SERVICE));
        m.put("entrance", Integer.valueOf((int) T_ENTRANCE));
        m.put("multistage", Integer.valueOf((int) T_MULTISTAGE));
        m.put("avatar_groups", Integer.valueOf((int) T_AVATAR_GROUPS));
        m.put("sys_button", 10001);
        m.put("button_container", Integer.valueOf((int) T_BUTTON_CONTAINER));
        m.put("main_view_container", Integer.valueOf((int) T_MAIN_VIEW_CONTAINER));
        m.put("shop_info_item", Integer.valueOf((int) T_SHOP_INFO_ITEM));
        m.put("custom_module", Integer.valueOf((int) T_CUSTOM_MODULE));
        m.put("tip", 30005);
        m.put("desc_quality", Integer.valueOf((int) T_QUALITY));
        m.put("desc_3d", Integer.valueOf((int) T_PICTURE_3D));
        m.put("desc_division", Integer.valueOf((int) T_DESC_DIVIDER));
        m.put("desc_store", Integer.valueOf((int) T_OFFLINE_STORE));
        m.put("desc_gif", 90001);
        m.put("weex", Integer.valueOf((int) T_WEEX));
        m.put("dinamic", Integer.valueOf((int) T_DINAMIC));
        m.put("dinamic_o2o", Integer.valueOf((int) T_DINAMIC_O2O));
        m.put("desc_weex_component", Integer.valueOf((int) T_VESSEL));
        m.put("title", Integer.valueOf((int) T_NEW_TITLE));
        m.put("pt_zongrentuan_ progressbar", Integer.valueOf((int) T_ZHONG_REN_TUAN_PROGRESSBAR));
        m.put("desc_threefigures_container", Integer.valueOf((int) T_VIDEO_CONTAINER));
        m.put("desc_video_info", Integer.valueOf((int) T_VIDEO_INFO));
        m.put("desc_charity", Integer.valueOf((int) T_DESC_CHARITY));
        m.put("tm_navi_bar", Integer.valueOf((int) T_TM_NAVI_BAR));
        m.put("tm_pic_gallery", Integer.valueOf((int) T_TM_PIC_GALLERY));
        m.put("tm_store_banner", Integer.valueOf((int) T_TM_STORE_BANNER));
        m.put("tm_store_recmd", Integer.valueOf((int) T_TM_STORE_RECMD));
        m.put("detail", Integer.valueOf((int) T_DETAIL));
        m.put("detailNavibar", Integer.valueOf((int) T_DETAIL_NAVI_BAR));
        m.put("detailNaviTabs", 21003);
        m.put("detailNaviItem", 21004);
        m.put("detailNaviTabItem", 21005);
        m.put("detailInfo", 21006);
        m.put(fjp.SCENE_WEEX_CONTAINER, 21007);
        m.put("detailDesc", 21008);
        m.put("descRecmd", 21009);
        m.put("detailHome", 21010);
        m.put("price_pack_trade", 80001);
    }

    public static int a(String str) {
        IpChange ipChange = $ipChange;
        if (ipChange instanceof IpChange) {
            return ((Number) ipChange.ipc$dispatch("f3a64c25", new Object[]{str})).intValue();
        }
        Integer num = m.get(str);
        if (num == null) {
            return 0;
        }
        return num.intValue();
    }
}
