package tb;

import com.alipay.security.mobile.alipayauthenticatorservice.message.Result;
import com.android.alibaba.ip.runtime.IpChange;
import com.taobao.android.job.core.task.e;
import com.taobao.android.job.core.task.g;
import com.taobao.android.launcher.biz.launcher.Cdo;
import com.taobao.android.launcher.biz.launcher.Cif;
import com.taobao.android.launcher.biz.launcher.InitAPM;
import com.taobao.android.launcher.biz.launcher.InitLifeCycle;
import com.taobao.android.launcher.biz.launcher.a;
import com.taobao.android.launcher.biz.launcher.aa;
import com.taobao.android.launcher.biz.launcher.ab;
import com.taobao.android.launcher.biz.launcher.ac;
import com.taobao.android.launcher.biz.launcher.ad;
import com.taobao.android.launcher.biz.launcher.ae;
import com.taobao.android.launcher.biz.launcher.af;
import com.taobao.android.launcher.biz.launcher.ag;
import com.taobao.android.launcher.biz.launcher.ah;
import com.taobao.android.launcher.biz.launcher.ai;
import com.taobao.android.launcher.biz.launcher.aj;
import com.taobao.android.launcher.biz.launcher.ak;
import com.taobao.android.launcher.biz.launcher.al;
import com.taobao.android.launcher.biz.launcher.am;
import com.taobao.android.launcher.biz.launcher.an;
import com.taobao.android.launcher.biz.launcher.ao;
import com.taobao.android.launcher.biz.launcher.ap;
import com.taobao.android.launcher.biz.launcher.aq;
import com.taobao.android.launcher.biz.launcher.ar;
import com.taobao.android.launcher.biz.launcher.as;
import com.taobao.android.launcher.biz.launcher.at;
import com.taobao.android.launcher.biz.launcher.au;
import com.taobao.android.launcher.biz.launcher.av;
import com.taobao.android.launcher.biz.launcher.aw;
import com.taobao.android.launcher.biz.launcher.ax;
import com.taobao.android.launcher.biz.launcher.ay;
import com.taobao.android.launcher.biz.launcher.az;
import com.taobao.android.launcher.biz.launcher.b;
import com.taobao.android.launcher.biz.launcher.ba;
import com.taobao.android.launcher.biz.launcher.bb;
import com.taobao.android.launcher.biz.launcher.bc;
import com.taobao.android.launcher.biz.launcher.bd;
import com.taobao.android.launcher.biz.launcher.be;
import com.taobao.android.launcher.biz.launcher.bf;
import com.taobao.android.launcher.biz.launcher.bg;
import com.taobao.android.launcher.biz.launcher.bh;
import com.taobao.android.launcher.biz.launcher.bi;
import com.taobao.android.launcher.biz.launcher.bj;
import com.taobao.android.launcher.biz.launcher.bk;
import com.taobao.android.launcher.biz.launcher.bl;
import com.taobao.android.launcher.biz.launcher.bm;
import com.taobao.android.launcher.biz.launcher.bn;
import com.taobao.android.launcher.biz.launcher.bo;
import com.taobao.android.launcher.biz.launcher.bp;
import com.taobao.android.launcher.biz.launcher.bq;
import com.taobao.android.launcher.biz.launcher.br;
import com.taobao.android.launcher.biz.launcher.bs;
import com.taobao.android.launcher.biz.launcher.bt;
import com.taobao.android.launcher.biz.launcher.bu;
import com.taobao.android.launcher.biz.launcher.bv;
import com.taobao.android.launcher.biz.launcher.bw;
import com.taobao.android.launcher.biz.launcher.bx;
import com.taobao.android.launcher.biz.launcher.by;
import com.taobao.android.launcher.biz.launcher.bz;
import com.taobao.android.launcher.biz.launcher.c;
import com.taobao.android.launcher.biz.launcher.ca;
import com.taobao.android.launcher.biz.launcher.cb;
import com.taobao.android.launcher.biz.launcher.cc;
import com.taobao.android.launcher.biz.launcher.cd;
import com.taobao.android.launcher.biz.launcher.ce;
import com.taobao.android.launcher.biz.launcher.cf;
import com.taobao.android.launcher.biz.launcher.cg;
import com.taobao.android.launcher.biz.launcher.ch;
import com.taobao.android.launcher.biz.launcher.ci;
import com.taobao.android.launcher.biz.launcher.cj;
import com.taobao.android.launcher.biz.launcher.ck;
import com.taobao.android.launcher.biz.launcher.cl;
import com.taobao.android.launcher.biz.launcher.cm;
import com.taobao.android.launcher.biz.launcher.cn;
import com.taobao.android.launcher.biz.launcher.co;
import com.taobao.android.launcher.biz.launcher.cp;
import com.taobao.android.launcher.biz.launcher.cq;
import com.taobao.android.launcher.biz.launcher.cr;
import com.taobao.android.launcher.biz.launcher.cs;
import com.taobao.android.launcher.biz.launcher.ct;
import com.taobao.android.launcher.biz.launcher.cu;
import com.taobao.android.launcher.biz.launcher.cv;
import com.taobao.android.launcher.biz.launcher.cw;
import com.taobao.android.launcher.biz.launcher.cx;
import com.taobao.android.launcher.biz.launcher.cy;
import com.taobao.android.launcher.biz.launcher.cz;
import com.taobao.android.launcher.biz.launcher.d;
import com.taobao.android.launcher.biz.launcher.da;
import com.taobao.android.launcher.biz.launcher.db;
import com.taobao.android.launcher.biz.launcher.dc;
import com.taobao.android.launcher.biz.launcher.dd;
import com.taobao.android.launcher.biz.launcher.de;
import com.taobao.android.launcher.biz.launcher.df;
import com.taobao.android.launcher.biz.launcher.dg;
import com.taobao.android.launcher.biz.launcher.dh;
import com.taobao.android.launcher.biz.launcher.di;
import com.taobao.android.launcher.biz.launcher.dj;
import com.taobao.android.launcher.biz.launcher.dk;
import com.taobao.android.launcher.biz.launcher.dl;
import com.taobao.android.launcher.biz.launcher.dm;
import com.taobao.android.launcher.biz.launcher.dn;
import com.taobao.android.launcher.biz.launcher.dp;
import com.taobao.android.launcher.biz.launcher.dq;
import com.taobao.android.launcher.biz.launcher.dr;
import com.taobao.android.launcher.biz.launcher.ds;
import com.taobao.android.launcher.biz.launcher.dt;
import com.taobao.android.launcher.biz.launcher.du;
import com.taobao.android.launcher.biz.launcher.dv;
import com.taobao.android.launcher.biz.launcher.dw;
import com.taobao.android.launcher.biz.launcher.dx;
import com.taobao.android.launcher.biz.launcher.dy;
import com.taobao.android.launcher.biz.launcher.dz;
import com.taobao.android.launcher.biz.launcher.ea;
import com.taobao.android.launcher.biz.launcher.eb;
import com.taobao.android.launcher.biz.launcher.ec;
import com.taobao.android.launcher.biz.launcher.ed;
import com.taobao.android.launcher.biz.launcher.ee;
import com.taobao.android.launcher.biz.launcher.ef;
import com.taobao.android.launcher.biz.launcher.eg;
import com.taobao.android.launcher.biz.launcher.eh;
import com.taobao.android.launcher.biz.launcher.ei;
import com.taobao.android.launcher.biz.launcher.ej;
import com.taobao.android.launcher.biz.launcher.ek;
import com.taobao.android.launcher.biz.launcher.el;
import com.taobao.android.launcher.biz.launcher.em;
import com.taobao.android.launcher.biz.launcher.en;
import com.taobao.android.launcher.biz.launcher.eo;
import com.taobao.android.launcher.biz.launcher.ep;
import com.taobao.android.launcher.biz.launcher.eq;
import com.taobao.android.launcher.biz.launcher.er;
import com.taobao.android.launcher.biz.launcher.es;
import com.taobao.android.launcher.biz.launcher.et;
import com.taobao.android.launcher.biz.launcher.eu;
import com.taobao.android.launcher.biz.launcher.ev;
import com.taobao.android.launcher.biz.launcher.ew;
import com.taobao.android.launcher.biz.launcher.ex;
import com.taobao.android.launcher.biz.launcher.ey;
import com.taobao.android.launcher.biz.launcher.ez;
import com.taobao.android.launcher.biz.launcher.f;
import com.taobao.android.launcher.biz.launcher.fa;
import com.taobao.android.launcher.biz.launcher.fb;
import com.taobao.android.launcher.biz.launcher.fc;
import com.taobao.android.launcher.biz.launcher.fd;
import com.taobao.android.launcher.biz.launcher.fe;
import com.taobao.android.launcher.biz.launcher.ff;
import com.taobao.android.launcher.biz.launcher.fg;
import com.taobao.android.launcher.biz.launcher.fh;
import com.taobao.android.launcher.biz.launcher.fi;
import com.taobao.android.launcher.biz.launcher.fj;
import com.taobao.android.launcher.biz.launcher.fk;
import com.taobao.android.launcher.biz.launcher.fl;
import com.taobao.android.launcher.biz.launcher.fm;
import com.taobao.android.launcher.biz.launcher.fn;
import com.taobao.android.launcher.biz.launcher.fo;
import com.taobao.android.launcher.biz.launcher.fp;
import com.taobao.android.launcher.biz.launcher.fq;
import com.taobao.android.launcher.biz.launcher.fr;
import com.taobao.android.launcher.biz.launcher.fs;
import com.taobao.android.launcher.biz.launcher.ft;
import com.taobao.android.launcher.biz.launcher.fu;
import com.taobao.android.launcher.biz.launcher.fv;
import com.taobao.android.launcher.biz.launcher.fw;
import com.taobao.android.launcher.biz.launcher.fx;
import com.taobao.android.launcher.biz.launcher.fy;
import com.taobao.android.launcher.biz.launcher.fz;
import com.taobao.android.launcher.biz.launcher.ga;
import com.taobao.android.launcher.biz.launcher.gb;
import com.taobao.android.launcher.biz.launcher.gc;
import com.taobao.android.launcher.biz.launcher.gd;
import com.taobao.android.launcher.biz.launcher.ge;
import com.taobao.android.launcher.biz.launcher.gf;
import com.taobao.android.launcher.biz.launcher.gg;
import com.taobao.android.launcher.biz.launcher.gh;
import com.taobao.android.launcher.biz.launcher.gi;
import com.taobao.android.launcher.biz.launcher.gj;
import com.taobao.android.launcher.biz.launcher.gk;
import com.taobao.android.launcher.biz.launcher.gl;
import com.taobao.android.launcher.biz.launcher.gm;
import com.taobao.android.launcher.biz.launcher.gn;
import com.taobao.android.launcher.biz.launcher.go;
import com.taobao.android.launcher.biz.launcher.gp;
import com.taobao.android.launcher.biz.launcher.gq;
import com.taobao.android.launcher.biz.launcher.gr;
import com.taobao.android.launcher.biz.launcher.gs;
import com.taobao.android.launcher.biz.launcher.gt;
import com.taobao.android.launcher.biz.launcher.gu;
import com.taobao.android.launcher.biz.launcher.gv;
import com.taobao.android.launcher.biz.launcher.gw;
import com.taobao.android.launcher.biz.launcher.gx;
import com.taobao.android.launcher.biz.launcher.gy;
import com.taobao.android.launcher.biz.launcher.gz;
import com.taobao.android.launcher.biz.launcher.h;
import com.taobao.android.launcher.biz.launcher.ha;
import com.taobao.android.launcher.biz.launcher.hb;
import com.taobao.android.launcher.biz.launcher.hc;
import com.taobao.android.launcher.biz.launcher.hd;
import com.taobao.android.launcher.biz.launcher.he;
import com.taobao.android.launcher.biz.launcher.hf;
import com.taobao.android.launcher.biz.launcher.hg;
import com.taobao.android.launcher.biz.launcher.hh;
import com.taobao.android.launcher.biz.launcher.hi;
import com.taobao.android.launcher.biz.launcher.hj;
import com.taobao.android.launcher.biz.launcher.hk;
import com.taobao.android.launcher.biz.launcher.hl;
import com.taobao.android.launcher.biz.launcher.hm;
import com.taobao.android.launcher.biz.launcher.hn;
import com.taobao.android.launcher.biz.launcher.ho;
import com.taobao.android.launcher.biz.launcher.hp;
import com.taobao.android.launcher.biz.launcher.hq;
import com.taobao.android.launcher.biz.launcher.hr;
import com.taobao.android.launcher.biz.launcher.hs;
import com.taobao.android.launcher.biz.launcher.ht;
import com.taobao.android.launcher.biz.launcher.hu;
import com.taobao.android.launcher.biz.launcher.hv;
import com.taobao.android.launcher.biz.launcher.hw;
import com.taobao.android.launcher.biz.launcher.hx;
import com.taobao.android.launcher.biz.launcher.hy;
import com.taobao.android.launcher.biz.launcher.hz;
import com.taobao.android.launcher.biz.launcher.i;
import com.taobao.android.launcher.biz.launcher.ia;
import com.taobao.android.launcher.biz.launcher.ib;
import com.taobao.android.launcher.biz.launcher.ic;
import com.taobao.android.launcher.biz.launcher.id;
import com.taobao.android.launcher.biz.launcher.ie;
import com.taobao.android.launcher.biz.launcher.ig;
import com.taobao.android.launcher.biz.launcher.ih;
import com.taobao.android.launcher.biz.launcher.ii;
import com.taobao.android.launcher.biz.launcher.ij;
import com.taobao.android.launcher.biz.launcher.ik;
import com.taobao.android.launcher.biz.launcher.il;
import com.taobao.android.launcher.biz.launcher.im;
import com.taobao.android.launcher.biz.launcher.in;
import com.taobao.android.launcher.biz.launcher.io;
import com.taobao.android.launcher.biz.launcher.ip;
import com.taobao.android.launcher.biz.launcher.iq;
import com.taobao.android.launcher.biz.launcher.ir;
import com.taobao.android.launcher.biz.launcher.is;
import com.taobao.android.launcher.biz.launcher.it;
import com.taobao.android.launcher.biz.launcher.iu;
import com.taobao.android.launcher.biz.launcher.iv;
import com.taobao.android.launcher.biz.launcher.iw;
import com.taobao.android.launcher.biz.launcher.ix;
import com.taobao.android.launcher.biz.launcher.iy;
import com.taobao.android.launcher.biz.launcher.iz;
import com.taobao.android.launcher.biz.launcher.j;
import com.taobao.android.launcher.biz.launcher.ja;
import com.taobao.android.launcher.biz.launcher.jb;
import com.taobao.android.launcher.biz.launcher.jc;
import com.taobao.android.launcher.biz.launcher.jd;
import com.taobao.android.launcher.biz.launcher.je;
import com.taobao.android.launcher.biz.launcher.jf;
import com.taobao.android.launcher.biz.launcher.jg;
import com.taobao.android.launcher.biz.launcher.jh;
import com.taobao.android.launcher.biz.launcher.ji;
import com.taobao.android.launcher.biz.launcher.jj;
import com.taobao.android.launcher.biz.launcher.jk;
import com.taobao.android.launcher.biz.launcher.jl;
import com.taobao.android.launcher.biz.launcher.jm;
import com.taobao.android.launcher.biz.launcher.jn;
import com.taobao.android.launcher.biz.launcher.jo;
import com.taobao.android.launcher.biz.launcher.jp;
import com.taobao.android.launcher.biz.launcher.jq;
import com.taobao.android.launcher.biz.launcher.jr;
import com.taobao.android.launcher.biz.launcher.js;
import com.taobao.android.launcher.biz.launcher.jt;
import com.taobao.android.launcher.biz.launcher.ju;
import com.taobao.android.launcher.biz.launcher.jv;
import com.taobao.android.launcher.biz.launcher.jw;
import com.taobao.android.launcher.biz.launcher.jx;
import com.taobao.android.launcher.biz.launcher.jy;
import com.taobao.android.launcher.biz.launcher.jz;
import com.taobao.android.launcher.biz.launcher.k;
import com.taobao.android.launcher.biz.launcher.ka;
import com.taobao.android.launcher.biz.launcher.kb;
import com.taobao.android.launcher.biz.launcher.kc;
import com.taobao.android.launcher.biz.launcher.kd;
import com.taobao.android.launcher.biz.launcher.ke;
import com.taobao.android.launcher.biz.launcher.kf;
import com.taobao.android.launcher.biz.launcher.kg;
import com.taobao.android.launcher.biz.launcher.kh;
import com.taobao.android.launcher.biz.launcher.l;
import com.taobao.android.launcher.biz.launcher.m;
import com.taobao.android.launcher.biz.launcher.n;
import com.taobao.android.launcher.biz.launcher.o;
import com.taobao.android.launcher.biz.launcher.p;
import com.taobao.android.launcher.biz.launcher.q;
import com.taobao.android.launcher.biz.launcher.r;
import com.taobao.android.launcher.biz.launcher.s;
import com.taobao.android.launcher.biz.launcher.t;
import com.taobao.android.launcher.biz.launcher.u;
import com.taobao.android.launcher.biz.launcher.v;
import com.taobao.android.launcher.biz.launcher.w;
import com.taobao.android.launcher.biz.launcher.x;
import com.taobao.android.launcher.biz.launcher.y;
import com.taobao.android.launcher.biz.launcher.z;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes.dex */
public class gun implements g<String, Void> {
    public static volatile transient /* synthetic */ IpChange $ipChange;

    /* renamed from: a  reason: collision with root package name */
    private final Map<String, e<String, Void>> f28463a;

    public gun() {
        gvt.a("LauncherProvider");
        this.f28463a = new HashMap((int) Result.ALIPAY_TEE_ERROR_ITEM_NOT_FOUND);
        this.f28463a.put("BoradcastAllSpark", new a("BoradcastAllSpark"));
        this.f28463a.put("BroadcastLogin", new b("BroadcastLogin"));
        this.f28463a.put("InitABGlobal", new c("InitABGlobal"));
        this.f28463a.put("InitAbilityKit", new l("InitAbilityKit"));
        this.f28463a.put("InitABTest", new d("InitABTest"));
        this.f28463a.put("InitAbtestAdapter", new m("InitAbtestAdapter"));
        this.f28463a.put("InitAccsAfterLogin", new n("InitAccsAfterLogin"));
        this.f28463a.put("InitAccsAfterLogout", new o("InitAccsAfterLogout"));
        this.f28463a.put("InitAccsInAppConnection", new p("InitAccsInAppConnection"));
        this.f28463a.put("InitAccsInAppConnectionB", new q("InitAccsInAppConnectionB"));
        this.f28463a.put("InitAccsOnBackground", new r("InitAccsOnBackground"));
        this.f28463a.put("InitAccsOnForeground", new s("InitAccsOnForeground"));
        this.f28463a.put("InitADaemonMonitor", new com.taobao.android.launcher.biz.launcher.e("InitADaemonMonitor"));
        this.f28463a.put("InitAgooLifeCycle", new t("InitAgooLifeCycle"));
        this.f28463a.put("InitAlimama", new w("InitAlimama"));
        this.f28463a.put("InitAliPrivacy", new u("InitAliPrivacy"));
        this.f28463a.put("InitAliSports", new v("InitAliSports"));
        this.f28463a.put("InitAlivfsMonitor", new x("InitAlivfsMonitor"));
        this.f28463a.put("InitAndroidMonkey", new y("InitAndroidMonkey"));
        this.f28463a.put("InitAPM", new InitAPM("InitAPM"));
        this.f28463a.put("InitAPMMin", new z("InitAPMMin"));
        this.f28463a.put("InitAPMRest", new f("InitAPMRest"));
        this.f28463a.put("InitAPMSecondary", new com.taobao.android.launcher.biz.launcher.g("InitAPMSecondary"));
        this.f28463a.put("InitAppBundleIdle", new ab("InitAppBundleIdle"));
        this.f28463a.put("InitAppBundleTrigger", new ac("InitAppBundleTrigger"));
        this.f28463a.put("InitAppRemoteGodEyeInitializer", new ad("InitAppRemoteGodEyeInitializer"));
        this.f28463a.put("InitAppRemoteOlympicInitializer", new ae("InitAppRemoteOlympicInitializer"));
        this.f28463a.put("InitAppRemoteOrangeInitializer", new af("InitAppRemoteOrangeInitializer"));
        this.f28463a.put("InitARCameraView", new h("InitARCameraView"));
        this.f28463a.put("InitArrayMap", new ag("InitArrayMap"));
        this.f28463a.put("InitAtlasClean", new ah("InitAtlasClean"));
        this.f28463a.put("InitAtlasServiceFinder", new ai("InitAtlasServiceFinder"));
        this.f28463a.put("InitAUE", new aa("InitAUE"));
        this.f28463a.put("InitAUEIdle", new kb("InitAUEIdle"));
        this.f28463a.put("InitAUS", new i("InitAUS"));
        this.f28463a.put("InitAutoSizeIdle", new aj("InitAutoSizeIdle"));
        this.f28463a.put("InitAVFS", new j("InitAVFS"));
        this.f28463a.put("InitAVSDK", new k("InitAVSDK"));
        this.f28463a.put("InitBasicParam", new ak("InitBasicParam"));
        this.f28463a.put("InitBehavirXStashes", new ji("InitBehavirXStashes"));
        this.f28463a.put("InitBehaviX", new al("InitBehaviX"));
        this.f28463a.put("InitBizErrorReporterOrange", new am("InitBizErrorReporterOrange"));
        this.f28463a.put("InitBootImage", new an("InitBootImage"));
        this.f28463a.put("InitBootImageIdle", new ao("InitBootImageIdle"));
        this.f28463a.put("InitBrowserProcess", new ap("InitBrowserProcess"));
        this.f28463a.put("InitBundleDebugSetting", new aq("InitBundleDebugSetting"));
        this.f28463a.put("InitCacheCleanerIdle", new ar("InitCacheCleanerIdle"));
        this.f28463a.put("InitCartBadge", new as("InitCartBadge"));
        this.f28463a.put("InitChangeAppIcon", new gw("InitChangeAppIcon"));
        this.f28463a.put("InitChannelCookieManager", new at("InitChannelCookieManager"));
        this.f28463a.put("InitClearSpeedFlag", new au("InitClearSpeedFlag"));
        this.f28463a.put("InitClipUrlWatcherLifeCycle", new av("InitClipUrlWatcherLifeCycle"));
        this.f28463a.put("InitCodeTrack", new aw("InitCodeTrack"));
        this.f28463a.put("InitColdLogin", new ax("InitColdLogin"));
        this.f28463a.put("InitComponents", new az("InitComponents"));
        this.f28463a.put("InitComponentState", new ay("InitComponentState"));
        this.f28463a.put("InitConfigCenterLifecycle", new ba("InitConfigCenterLifecycle"));
        this.f28463a.put("InitCookieManager", new bb("InitCookieManager"));
        this.f28463a.put("InitCrashSDKOrange", new bc("InitCrashSDKOrange"));
        this.f28463a.put("InitDAGPointsReport", new bd("InitDAGPointsReport"));
        this.f28463a.put("InitDAIColdStartup", new be("InitDAIColdStartup"));
        this.f28463a.put("InitDAIColdStartupB", new bf("InitDAIColdStartupB"));
        this.f28463a.put("InitDAIFirstInstall", new bg("InitDAIFirstInstall"));
        this.f28463a.put("InitDesktopTaskTrigger", new bn("InitDesktopTaskTrigger"));
        this.f28463a.put("InitDesktopWidget", new bo("InitDesktopWidget"));
        this.f28463a.put("InitDetailLauncher", new bp("InitDetailLauncher"));
        this.f28463a.put("InitDeviceScore", new bq("InitDeviceScore"));
        this.f28463a.put("InitDiagnose", new br("InitDiagnose"));
        this.f28463a.put("InitDowngrade", new bs("InitDowngrade"));
        this.f28463a.put("InitDownloader", new bt("InitDownloader"));
        this.f28463a.put("InitDWBase", new bh("InitDWBase"));
        this.f28463a.put("InitDWIdle", new bi("InitDWIdle"));
        this.f28463a.put("InitDXMin", new hb("InitDXMin"));
        this.f28463a.put("InitDXOpt", new jk("InitDXOpt"));
        this.f28463a.put("InitDXV2", new bj("InitDXV2"));
        this.f28463a.put("InitDXV2Delay", new bk("InitDXV2Delay"));
        this.f28463a.put("InitDXV3", new bl("InitDXV3"));
        this.f28463a.put("InitDXV3Delay", new bm("InitDXV3Delay"));
        this.f28463a.put("InitEditionSwitcher", new en("InitEditionSwitcher"));
        this.f28463a.put("InitElder", new bu("InitElder"));
        this.f28463a.put("InitEnv", new bv("InitEnv"));
        this.f28463a.put("InitFamily", new bw("InitFamily"));
        this.f28463a.put("InitFastEmptyTask", new bx("InitFastEmptyTask"));
        this.f28463a.put("InitFeedbackJsBridge", new by("InitFeedbackJsBridge"));
        this.f28463a.put("InitFontSetting", new bz("InitFontSetting"));
        this.f28463a.put("InitFontSettingIdle", new ca("InitFontSettingIdle"));
        this.f28463a.put("InitGalileo", new cb("InitGalileo"));
        this.f28463a.put("InitH5Request", new cc("InitH5Request"));
        this.f28463a.put("InitHomeCache", new cd("InitHomeCache"));
        this.f28463a.put("InitHomeDinamicX2Launcher", new ce("InitHomeDinamicX2Launcher"));
        this.f28463a.put("InitHomeDinamicX2LauncherDelay", new cf("InitHomeDinamicX2LauncherDelay"));
        this.f28463a.put("InitHomeDinamicX3Launcher", new cg("InitHomeDinamicX3Launcher"));
        this.f28463a.put("InitHomeDinamicX3LauncherDelay", new ch("InitHomeDinamicX3LauncherDelay"));
        this.f28463a.put("InitHomeFrameLauncher", new jv("InitHomeFrameLauncher"));
        this.f28463a.put("InitHomeGatewayLauncher", new ci("InitHomeGatewayLauncher"));
        this.f28463a.put("InitHomeGatewayLauncherDelay", new cj("InitHomeGatewayLauncherDelay"));
        this.f28463a.put("InitHomeIdleLauncher", new ck("InitHomeIdleLauncher"));
        this.f28463a.put("InitHomeLauncher", new cl("InitHomeLauncher"));
        this.f28463a.put("InitHomeLauncherDelay", new cm("InitHomeLauncherDelay"));
        this.f28463a.put("InitHomeMin", new js("InitHomeMin"));
        this.f28463a.put("InitHomeMinOpt", new jw("InitHomeMinOpt"));
        this.f28463a.put("InitHomePreAdvLauncher", new cn("InitHomePreAdvLauncher"));
        this.f28463a.put("InitHomePreAdvLauncherDelay", new co("InitHomePreAdvLauncherDelay"));
        this.f28463a.put("InitHomePreCreateNativeView", new jt("InitHomePreCreateNativeView"));
        this.f28463a.put("InitHomePreCreateViewLauncher", new cp("InitHomePreCreateViewLauncher"));
        this.f28463a.put("InitHomePreParamsLauncher", new cq("InitHomePreParamsLauncher"));
        this.f28463a.put("InitHomePreParamsLauncherDelay", new cr("InitHomePreParamsLauncherDelay"));
        this.f28463a.put("InitHomePreRequestLauncher", new cs("InitHomePreRequestLauncher"));
        this.f28463a.put("InitHomeResumed", new eo("InitHomeResumed"));
        this.f28463a.put("InitHomeSwitchLauncher", new ct("InitHomeSwitchLauncher"));
        this.f28463a.put("InitHomeSwitchLauncherDelay", new cu("InitHomeSwitchLauncherDelay"));
        this.f28463a.put("InitHomeTaskCompleted", new cv("InitHomeTaskCompleted"));
        this.f28463a.put("InitHomeThreadInitLauncher", new jx("InitHomeThreadInitLauncher"));
        this.f28463a.put("InitHomeVisible", new ha("InitHomeVisible"));
        this.f28463a.put("InitHuDongIdle", new cw("InitHuDongIdle"));
        this.f28463a.put("InitJTrack", new cx("InitJTrack"));
        this.f28463a.put("InitKeepAlive", new cy("InitKeepAlive"));
        this.f28463a.put("InitLaunchdogAlarm", new db("InitLaunchdogAlarm"));
        this.f28463a.put("InitLauncher", new dc("InitLauncher"));
        this.f28463a.put("InitLaunchStart", new cz("InitLaunchStart"));
        this.f28463a.put("InitLaunchTrace", new da("InitLaunchTrace"));
        this.f28463a.put("InitLifeCycle", new InitLifeCycle("InitLifeCycle"));
        this.f28463a.put("InitLinkInAction", new kc("InitLinkInAction"));
        this.f28463a.put("InitLinkLifeCycle", new dd("InitLinkLifeCycle"));
        this.f28463a.put("InitLinkLogin", new de("InitLinkLogin"));
        this.f28463a.put("InitLinkManager", new df("InitLinkManager"));
        this.f28463a.put("InitLinkManagerB", new dg("InitLinkManagerB"));
        this.f28463a.put("InitLinkManagerC", new dh("InitLinkManagerC"));
        this.f28463a.put("InitLinkManagerHomeFinish", new jr("InitLinkManagerHomeFinish"));
        this.f28463a.put("InitLinkMessageBundle", new ib("InitLinkMessageBundle"));
        this.f28463a.put("InitLinkRewriter", new di("InitLinkRewriter"));
        this.f28463a.put("InitLinkSmart", new dj("InitLinkSmart"));
        this.f28463a.put("InitLinkTriverNetwork", new dk("InitLinkTriverNetwork"));
        this.f28463a.put("InitLinkUtCheck", new dl("InitLinkUtCheck"));
        this.f28463a.put("InitLivePopup", new dm("InitLivePopup"));
        this.f28463a.put("InitLocalization", new ju("InitLocalization"));
        this.f28463a.put("InitLogin", new dn("InitLogin"));
        this.f28463a.put("InitLoginLifeCycle", new Cdo("InitLoginLifeCycle"));
        this.f28463a.put("InitLoginParam", new dp("InitLoginParam"));
        this.f28463a.put("InitLoginSessionCheck", new kg("InitLoginSessionCheck"));
        this.f28463a.put("InitLoginSessionValid", new dq("InitLoginSessionValid"));
        this.f28463a.put("InitManufacturer", new ds("InitManufacturer"));
        this.f28463a.put("InitMemKeeper", new dt("InitMemKeeper"));
        this.f28463a.put("InitMessage", new du("InitMessage"));
        this.f28463a.put("InitMessagePreload", new dv("InitMessagePreload"));
        this.f28463a.put("InitMetricKit", new dw("InitMetricKit"));
        this.f28463a.put("InitMetricKitIdle", new dx("InitMetricKitIdle"));
        this.f28463a.put("InitMiniPay", new dy("InitMiniPay"));
        this.f28463a.put("InitMotuCrash", new dz("InitMotuCrash"));
        this.f28463a.put("InitMsgKeepAlive", new ea("InitMsgKeepAlive"));
        this.f28463a.put("InitMTBPreload", new dr("InitMTBPreload"));
        this.f28463a.put("InitMtop", new eb("InitMtop"));
        this.f28463a.put("InitMtopDelay", new ec("InitMtopDelay"));
        this.f28463a.put("InitMtopLifeCycle", new ed("InitMtopLifeCycle"));
        this.f28463a.put("InitMtopMin", new jy("InitMtopMin"));
        this.f28463a.put("InitMtopMultiLang", new kd("InitMtopMultiLang"));
        this.f28463a.put("InitMtopSSRLink", new jn("InitMtopSSRLink"));
        this.f28463a.put("InitNav", new ef("InitNav"));
        this.f28463a.put("InitNavigationIdle", new he("InitNavigationIdle"));
        this.f28463a.put("InitNavProcessorPreloadIdle", new ja("InitNavProcessorPreloadIdle"));
        this.f28463a.put("InitNavSharePreProcess", new eg("InitNavSharePreProcess"));
        this.f28463a.put("InitNDIdle", new ee("InitNDIdle"));
        this.f28463a.put("InitNegativeMonitor", new eh("InitNegativeMonitor"));
        this.f28463a.put("InitNegativeProblems", new ei("InitNegativeProblems"));
        this.f28463a.put("InitNetwork", new ej("InitNetwork"));
        this.f28463a.put("InitNetworkMin", new jz("InitNetworkMin"));
        this.f28463a.put("InitNetworkStrategy", new ek("InitNetworkStrategy"));
        this.f28463a.put("InitNewDetail", new el("InitNewDetail"));
        this.f28463a.put("InitNextRpc", new em("InitNextRpc"));
        this.f28463a.put("InitOrangeAfterLogin", new ep("InitOrangeAfterLogin"));
        this.f28463a.put("InitOrangeAfterLogout", new eq("InitOrangeAfterLogout"));
        this.f28463a.put("InitOrangeConfig", new er("InitOrangeConfig"));
        this.f28463a.put("InitOrangeConfigLaunched", new es("InitOrangeConfigLaunched"));
        this.f28463a.put("InitOrangeDelay", new et("InitOrangeDelay"));
        this.f28463a.put("InitOrangeFetch", new ka("InitOrangeFetch"));
        this.f28463a.put("InitOrangeIdle", new eu("InitOrangeIdle"));
        this.f28463a.put("InitOvsHomeIdle", new ev("InitOvsHomeIdle"));
        this.f28463a.put("InitPassiveLocation", new ey("InitPassiveLocation"));
        this.f28463a.put("InitPermissionBridge", new ez("InitPermissionBridge"));
        this.f28463a.put("InitPermissionIdle", new fa("InitPermissionIdle"));
        this.f28463a.put("InitPGInitTask", new ew("InitPGInitTask"));
        this.f28463a.put("InitPHAIdle", new ex("InitPHAIdle"));
        this.f28463a.put("InitPhenix", new fb("InitPhenix"));
        this.f28463a.put("InitPhenixApng", new fc("InitPhenixApng"));
        this.f28463a.put("InitPhenixApngDelay", new fd("InitPhenixApngDelay"));
        this.f28463a.put("InitPhenixApngOpt", new fe("InitPhenixApngOpt"));
        this.f28463a.put("InitPhenixAvif", new ff("InitPhenixAvif"));
        this.f28463a.put("InitPhenixBuild", new fg("InitPhenixBuild"));
        this.f28463a.put("InitPhenixBuildDelay", new fh("InitPhenixBuildDelay"));
        this.f28463a.put("InitPhenixDelay", new fi("InitPhenixDelay"));
        this.f28463a.put("InitPhenixGif", new fj("InitPhenixGif"));
        this.f28463a.put("InitPhenixHeif", new fk("InitPhenixHeif"));
        this.f28463a.put("InitPhenixHeifDelay", new fl("InitPhenixHeifDelay"));
        this.f28463a.put("InitPhenixHeifOpt", new fm("InitPhenixHeifOpt"));
        this.f28463a.put("InitPhenixMin", new jb("InitPhenixMin"));
        this.f28463a.put("InitPhenixNotifyLaunchFinish", new jg("InitPhenixNotifyLaunchFinish"));
        this.f28463a.put("InitPhenixScheduler", new fn("InitPhenixScheduler"));
        this.f28463a.put("InitPhenixSchedulerDelay", new fo("InitPhenixSchedulerDelay"));
        this.f28463a.put("InitPhenixWebp", new fp("InitPhenixWebp"));
        this.f28463a.put("InitPopCenter", new fq("InitPopCenter"));
        this.f28463a.put("InitPopConfigLoadTask", new jl("InitPopConfigLoadTask"));
        this.f28463a.put("InitPopMin", new jj("InitPopMin"));
        this.f28463a.put("InitPopPost", new fr("InitPopPost"));
        this.f28463a.put("InitPopPre", new fs("InitPopPre"));
        this.f28463a.put("InitPowerMessage", new ft("InitPowerMessage"));
        this.f28463a.put("InitPreEnv", new fu("InitPreEnv"));
        this.f28463a.put("InitPreloadIdle", new fv("InitPreloadIdle"));
        this.f28463a.put("InitPreloadNav", new fw("InitPreloadNav"));
        this.f28463a.put("InitProcessInfos", new fx("InitProcessInfos"));
        this.f28463a.put("InitProtodbDaemon", new fy("InitProtodbDaemon"));
        this.f28463a.put("InitProtoDBMin", new jh("InitProtoDBMin"));
        this.f28463a.put("InitPurchaseIdle", new fz("InitPurchaseIdle"));
        this.f28463a.put("InitPush", new ga("InitPush"));
        this.f28463a.put("InitQuality", new gb("InitQuality"));
        this.f28463a.put("InitRecPrivacy", new gc("InitRecPrivacy"));
        this.f28463a.put("InitRemoteSo", new gd("InitRemoteSo"));
        this.f28463a.put("InitRemoteSoIdle", new ge("InitRemoteSoIdle"));
        this.f28463a.put("InitResourceGuardian", new gf("InitResourceGuardian"));
        this.f28463a.put("InitRestOrandleIdle", new gg("InitRestOrandleIdle"));
        this.f28463a.put("InitRevisionSwitch", new gh("InitRevisionSwitch"));
        this.f28463a.put("InitRevisionTrack", new gi("InitRevisionTrack"));
        this.f28463a.put("InitRsoLink", new gj("InitRsoLink"));
        this.f28463a.put("InitRsoLinkFinish", new gk("InitRsoLinkFinish"));
        this.f28463a.put("InitSafeMode", new gm("InitSafeMode"));
        this.f28463a.put("InitSafeModeOrange", new gn("InitSafeModeOrange"));
        this.f28463a.put("InitScreenConfig", new go("InitScreenConfig"));
        this.f28463a.put("InitScriptManager", new gp("InitScriptManager"));
        this.f28463a.put("InitSearchColdLaunchTask", new jm("InitSearchColdLaunchTask"));
        this.f28463a.put("InitSecIO", new gq("InitSecIO"));
        this.f28463a.put("InitSecurityManager", new gr("InitSecurityManager"));
        this.f28463a.put("InitSGJpgProcess", new gl("InitSGJpgProcess"));
        this.f28463a.put("InitShareFeedbackLaunched", new gs("InitShareFeedbackLaunched"));
        this.f28463a.put("InitShop", new gt("InitShop"));
        this.f28463a.put("InitShopRule", new gu("InitShopRule"));
        this.f28463a.put("InitShopRuleOpt", new gv("InitShopRuleOpt"));
        this.f28463a.put("InitStatistics", new gx("InitStatistics"));
        this.f28463a.put("InitStatisticsDump", new gy("InitStatisticsDump"));
        this.f28463a.put("InitStatisticsSubmit", new gz("InitStatisticsSubmit"));
        this.f28463a.put("InitTab2ColdLaunchTask", new hh("InitTab2ColdLaunchTask"));
        this.f28463a.put("InitTab2Preload", new hi("InitTab2Preload"));
        this.f28463a.put("InitTaoLiveColdLaunchTask", new hj("InitTaoLiveColdLaunchTask"));
        this.f28463a.put("InitTaoLiveIdle", new hk("InitTaoLiveIdle"));
        this.f28463a.put("InitTaoLog", new hl("InitTaoLog"));
        this.f28463a.put("InitTaoLogForAccs", new hm("InitTaoLogForAccs"));
        this.f28463a.put("InitTBExecutor", new hc("InitTBExecutor"));
        this.f28463a.put("InitTBWidget", new hd("InitTBWidget"));
        this.f28463a.put("InitThemeKit", new hy("InitThemeKit"));
        this.f28463a.put("InitTimeStampManagerStart", new hn("InitTimeStampManagerStart"));
        this.f28463a.put("InitTimeStampManagerStop", new ho("InitTimeStampManagerStop"));
        this.f28463a.put("InitTMQOlympic", new hf("InitTMQOlympic"));
        this.f28463a.put("InitTMSEarly", new jo("InitTMSEarly"));
        this.f28463a.put("InitTMSForeground", new kh("InitTMSForeground"));
        this.f28463a.put("InitTMSIdle", new jp("InitTMSIdle"));
        this.f28463a.put("InitTMSNecessary", new jq("InitTMSNecessary"));
        this.f28463a.put("InitTMSResume", new kf("InitTMSResume"));
        this.f28463a.put("InitTNet", new hg("InitTNet"));
        this.f28463a.put("InitToastHook", new hp("InitToastHook"));
        this.f28463a.put("InitTriver", new hq("InitTriver"));
        this.f28463a.put("InitTriverLightWeight", new hr("InitTriverLightWeight"));
        this.f28463a.put("InitTriverNav", new hs("InitTriverNav"));
        this.f28463a.put("InitTucaobarIdle", new jf("InitTucaobarIdle"));
        this.f28463a.put("InitTurboBootBackground", new ht("InitTurboBootBackground"));
        this.f28463a.put("InitTurboBootChannel", new hu("InitTurboBootChannel"));
        this.f28463a.put("InitTurboBootEarly", new hv("InitTurboBootEarly"));
        this.f28463a.put("InitTurboBootIdle", new hw("InitTurboBootIdle"));
        this.f28463a.put("InitUCDecompress", new hx("InitUCDecompress"));
        this.f28463a.put("InitUCParam", new hz("InitUCParam"));
        this.f28463a.put("InitUCParamB", new ia("InitUCParamB"));
        this.f28463a.put("InitUCSoInject", new ic("InitUCSoInject"));
        this.f28463a.put("InitUCSoInjectB", new id("InitUCSoInjectB"));
        this.f28463a.put("InitUCWebView", new ie("InitUCWebView"));
        this.f28463a.put("InitUpdate", new ig("InitUpdate"));
        this.f28463a.put("InitUpdateLightweight", new ih("InitUpdateLightweight"));
        this.f28463a.put("InitURLRewrite", new Cif("InitURLRewrite"));
        this.f28463a.put("InitUt", new ii("InitUt"));
        this.f28463a.put("InitUt4Aplus", new ij("InitUt4Aplus"));
        this.f28463a.put("InitUtNotify", new ke("InitUtNotify"));
        this.f28463a.put("InitVirtualThreadIdleLauncher", new ik("InitVirtualThreadIdleLauncher"));
        this.f28463a.put("InitVirtualThreadLauncher", new il("InitVirtualThreadLauncher"));
        this.f28463a.put("InitVoiceAssistant", new im("InitVoiceAssistant"));
        this.f28463a.put("InitVoiceAssistantIdle", new in("InitVoiceAssistantIdle"));
        this.f28463a.put("InitWeex", new io("InitWeex"));
        this.f28463a.put("InitWeex2BootFinish", new ip("InitWeex2BootFinish"));
        this.f28463a.put("InitWeexIdle", new iq("InitWeexIdle"));
        this.f28463a.put("InitWeexNoSucks", new ir("InitWeexNoSucks"));
        this.f28463a.put("InitWeexSmooth", new is("InitWeexSmooth"));
        this.f28463a.put("InitWeexSmoothBootFinish", new it("InitWeexSmoothBootFinish"));
        this.f28463a.put("InitWeexSmoothDelay", new iu("InitWeexSmoothDelay"));
        this.f28463a.put("InitWeexSmoothLaunched", new iv("InitWeexSmoothLaunched"));
        this.f28463a.put("InitWeexSmoothOpt", new iw("InitWeexSmoothOpt"));
        this.f28463a.put("InitWelcome", new ix("InitWelcome"));
        this.f28463a.put("InitWindvane", new iy("InitWindvane"));
        this.f28463a.put("InitWindvaneSecondary", new iz("InitWindvaneSecondary"));
        this.f28463a.put("InitXState", new jc("InitXState"));
        this.f28463a.put("InitZCacheColdStartup", new jd("InitZCacheColdStartup"));
        this.f28463a.put("InitZCacheFirstInstall", new je("InitZCacheFirstInstall"));
        gvt.a();
    }

    @Override // com.taobao.android.job.core.task.g
    public e<String, Void> a(String str) {
        IpChange ipChange = $ipChange;
        return ipChange instanceof IpChange ? (e) ipChange.ipc$dispatch("31278f8d", new Object[]{this, str}) : this.f28463a.get(str);
    }
}
